"""Reminders v0 — the first machinery that keeps a conversational
promise automatically.

A promise Theo makes in conversation ("토요일 9시에 알려줄게") becomes
a row (db.create_reminder, seeded by the operator for now); a Render
cron hits POST /reminders/tick every 15 minutes; due rows fire through
sms.send_nudge, so the outbound message is generated by the user's own
companion prompt with their history — it sounds like Theo continuing
the conversation, not an alarm.

Time model: fire_at is stored as aware UTC ISO. Recurrence advances in
America/Los_Angeles wall-clock time (the pilot users' timezone), so a
weekday 16:30 reminder stays 16:30 local across DST.

v1 (not built): Theo registers reminders itself via a reply marker,
the way [IGNITION:]/[PLAN:] markers worked — the contract point is
already here (create_reminder), only the extraction is missing.
"""

from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo

import db

LA = ZoneInfo("America/Los_Angeles")


def parse_operator_time(spec):
    """Operator-friendly time input → aware UTC ISO. A spec with an
    explicit offset (or trailing Z) is taken as written; a naked
    'YYYY-MM-DDTHH:MM' is LA wall-clock time."""
    spec = spec.strip().replace(" ", "T")
    if spec.endswith("Z"):
        spec = spec[:-1] + "+00:00"
    dt = datetime.fromisoformat(spec)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=LA)
    return dt.astimezone(timezone.utc).isoformat()


def next_weekday_fire(fire_at_iso, now=None):
    """The next Mon-Fri occurrence of fire_at's LA wall-clock time
    strictly after both fire_at and now — advancing from the
    SCHEDULED time (no drift), but never into the past (a downed
    server catches up to the future, it does not replay missed
    days)."""
    now = now or datetime.now(timezone.utc)
    local = datetime.fromisoformat(fire_at_iso).astimezone(LA)
    day = local.date()
    while True:
        day += timedelta(days=1)
        if day.weekday() >= 5:  # Sat=5, Sun=6
            continue
        # DST-safe: rebuild the wall-clock time on the new date
        # (adding timedelta to an aware datetime shifts wall-clock
        # across DST boundaries; reconstructing does not).
        cand = datetime(day.year, day.month, day.day, local.hour,
                        local.minute, local.second, tzinfo=LA)
        utc = cand.astimezone(timezone.utc)
        if utc > now:
            return utc.isoformat()


def run_due(now=None):
    """Fire every due reminder. Returns a report list for the tick
    endpoint. A failed send still closes/advances the row —
    send_nudge logs its own failures and a reminder must never
    fire-loop."""
    import sms

    now = now or datetime.now(timezone.utc)
    report = []
    for r in db.get_due_reminders(now.isoformat()):
        text = sms.send_nudge(r["user_id"], r["instruction"])
        next_fire = None
        if (r["recur"] or "").strip() == "weekdays":
            next_fire = next_weekday_fire(r["fire_at"], now=now)
        db.mark_reminder_fired(r["id"], next_fire_at=next_fire,
                               sent=bool(text))
        db.log_event(r["user_id"], "reminder_fired",
                     {"reminder_id": r["id"], "sent": bool(text),
                      "next_fire_at": next_fire or "",
                      "instruction": r["instruction"][:200]},
                     source="reminders")
        report.append({"reminder_id": r["id"], "user_id": r["user_id"],
                       "sent": bool(text),
                       "next_fire_at": next_fire or ""})
    return report
