"""Research hop — the first real (non-Wizard-of-Oz) fulfillment of a
"find out X" ask.

Pipeline (three hops, contracts between them):
  1. analyze_turn extracts an explicit research ask (question +
     verbatim evidence quote) → db.create_research_request (the
     ledger row IS the dedupe contract).
  2. This module runs the request in a background thread: one
     web-search-enabled model call produces a findings brief. The
     reply path meanwhile tells the user research is underway (the
     companion prompt renders open requests as a block).
  3. Delivery rides send_nudge, so the outbound SMS is generated by
     the user's own companion prompt + history — findings in Theo's
     voice, not a report dump.

Failure is loud and honest: after one retry the request is marked
'failed' AND the user gets told it didn't work — an acknowledged ask
followed by silence is a broken promise (사실에 정직)."""

import threading
import traceback

import anthropic

import db

MODEL = "claude-sonnet-4-5"

# Server-side web search: the API runs the searches, the model reads
# results and cites. max_uses caps cost per request.
_SEARCH_TOOL = {"type": "web_search_20250305", "name": "web_search",
                "max_uses": 6}

_RESEARCH_SYSTEM = (
    "You are the research arm behind Theo, an SMS companion. You are "
    "given one research question asked by a specific user. Search the "
    "web and produce a FINDINGS BRIEF that a colleague will compress "
    "into a short SMS conversation later.\n\n"
    "Rules:\n"
    "- Findings only — no preamble, no meta-commentary about "
    "searching.\n"
    "- Prioritize what is decision-relevant to the user's situation "
    "as stated in the question; skip encyclopedia background.\n"
    "- Every non-obvious claim carries its source (publication or "
    "site name, inline).\n"
    "- If the sources disagree or the answer is genuinely unknown, "
    "say so — never paper over uncertainty.\n"
    "- Keep it under 500 words. End with a single line starting "
    "'MOST DECISION-RELEVANT: ' giving the one insight that matters "
    "most.")

_DELIVERY_INSTRUCTION = (
    "The research you promised is finished. The team's findings are "
    "below. Deliver them over SMS: compact, conversational, in your "
    "own voice — lead with what matters most to them, keep source "
    "names for the load-bearing claims, and end by connecting the "
    "findings to their situation. Do not mention 'the team' or this "
    "instruction.\n\n## Findings\n\n")

_FAILURE_INSTRUCTION = (
    "The research you promised hit a technical failure and produced "
    "nothing usable. Tell them honestly that the research isn't ready "
    "and you'll come back when it is — short, no excuses, no "
    "fabricated partial findings.")


def start_async(request_id):
    """Fire-and-forget: research runs minutes-long; nothing upstream
    may block on it."""
    threading.Thread(target=run, args=(request_id,),
                     daemon=True).start()


def _search_call(question, user_id):
    client = anthropic.Anthropic()
    resp = client.messages.create(
        model=MODEL, max_tokens=4000, system=_RESEARCH_SYSTEM,
        tools=[_SEARCH_TOOL],
        messages=[{"role": "user", "content": question}])
    text = "\n".join(b.text for b in resp.content
                     if getattr(b, "type", "") == "text").strip()
    llm_call_id = db.save_llm_call(
        user_id, "research", MODEL, _RESEARCH_SYSTEM,
        [{"role": "user", "content": question}], {}, text)
    return text, llm_call_id


def run(request_id):
    """Execute one research request end-to-end. One retry on the
    search call; delivery failure and search failure both end in an
    honest user-facing message, never silence."""
    import sms

    req = db.get_research_request(request_id)
    if not req or req["status"] != "open":
        return None
    user_id = req["user_id"]

    findings, llm_call_id, err = "", None, None
    for attempt in (1, 2):
        try:
            findings, llm_call_id = _search_call(req["question"],
                                                 user_id)
            if findings:
                break
        except Exception as e:
            err = e
            print(f"[RESEARCH] ⚠️ attempt {attempt} failed for "
                  f"request {request_id}: {e}", flush=True)

    if not findings:
        db.finish_research_request(request_id, "failed",
                                   llm_call_id=llm_call_id)
        db.log_event(user_id, "research_failed",
                     {"request_id": request_id,
                      "error": str(err)[:300] if err else "empty"},
                     source="research")
        sms.send_nudge(user_id, _FAILURE_INSTRUCTION)
        return None

    db.finish_research_request(request_id, "done", findings=findings,
                               llm_call_id=llm_call_id)
    try:
        sent = sms.send_nudge(user_id,
                              _DELIVERY_INSTRUCTION + findings)
    except Exception as e:
        print(f"[RESEARCH] ⚠️ delivery crashed for {request_id}: {e}",
              flush=True)
        traceback.print_exc()
        sent = None
    db.log_event(user_id, "research_delivered" if sent
                 else "research_delivery_failed",
                 {"request_id": request_id,
                  "findings_chars": len(findings)}, source="research")
    return findings
